channels:
        - bioconda
        - defaults
        - conda-forge

dependencies:
        - invoke
        - argparse
        - cython
        - numpy
        - pandas
        - scipy
        - scikit-learn
        - sqlitedict
        - regex
        - HTSeq
        - pysam
        - setuptools
        - pympler
        - seaborn       
        - star
        - samtools
        - openssl
